#!/bin/bash
exec < /dev/tty

# Coletando o nome do branch atual
branch_name=$(git branch | grep "*" | sed "s/\* //")

# Coletando o nome do branch que foi mergeado
reflog_message=$(git reflog -1)
merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")

# Se o branch for do master, não faça nada.
if [[ $merged_branch_name = "master" ]]; then
    exit 0
fi

echo " "
echo "Você acabou de realizar um merge do branch \"$merged_branch_name\" para o \"$branch_name\". "

read -p "Deseja excluir o branch \"$merged_branch_name\" ? (y/N) " answer

if [[ "$answer" == "y" ]]; then

    # Excluindo o branch local
    echo "Excluindo o branch localmente \"$merged_branch_name\""
    git branch -d $merged_branch_name

    # Excluindo o branch remoto
    echo "Excluindo o branch remotamente"
    git push origin --delete $merged_branch_name
    exit 1
else
    echo "Branch -> \"$merged_branch_name\" mantido."
fi
